/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'rudy' at '4/11/16 10:04' with Gradle 3.0
 *
 * @author rudy, @date 4/11/16 10:04
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
